### ISSUE TITLE
[💡 idea: ] ability to ignore sections of markdown akin to markdownlint

### ISSUE THREAD

**Issue by RolfMoleman** [nvuillam/markdown-table-formatter#15]
I really like the formatter. Howeverm, it can cause a continuous PR loop which consumes excessive action minutes, when used with tools such as terraform-docs. 

# Why
Terraform docs gnerates terrform documentation into markdown, but then when using megalinter the markdown-table-formatter picks up that the table is incorrectly formatted and attempts to reformat it. which then on our rlelease pieplien causes terraform-docs to run afgain, createing a fresh (or reopening) a pr from megalinter where the only changes are from this. 

# What
would it be possible to implement markdown comment blocks where this ignores the code between them akin to `<!-- markdownlint-enable -->` and `<!-- markdownlint-disable -->` in markdownlint or `<!-- prettier-ignore-start -->` and `<!-- prettier-ignore-end -->` in prettier

**Comment by nvuillam** [comment]
Hi @RolfMoleman , thanks for your feedback :)

markdown-table-formatter relies on [markdown-table-prettify](https://www.npmjs.com/package/markdown-table-prettify) 

According to its documentation, the feature you'd like is.... already existing :)

```
Support `code blocks` and ignore blocks with <!-- markdown-table-prettify-ignore-start --> and <!-- markdown-table-prettify-ignore-end -->.`
```

Please can you confirm it works, so I can update markdown-table-formatter documentation ? :)

**Comment by RolfMoleman** [comment]
Hi @nvuillam under initial testing this seems to work as expected.

**Comment by nvuillam** [comment]
@RolfMoleman great :)
Would you like to make a pull request to update the doc? ^^

**Comment by RolfMoleman** [comment]
@nvuillam Sure why not 😄
