### ISSUE TITLE
Support for ignoring specific doc sections

### ISSUE THREAD

**Issue by tpansino** [nvuillam/markdown-table-formatter#6]
Related to https://github.com/darkriszty/MarkdownTablePrettify-VSCodeExt/issues/56.

The maintainer of the MarkdownTablePrettify extension was kind enough to add my requested support for ignoring blocks via code comments in release v3.4.0.

How difficult would it be to upgrade this tool to use the new package version so this functionality can be used via the Mega Linter? Happy to provide a PR if that helps.

**Comment by nvuillam** [comment]
@tpansino  you can make a PR on this repo to upgrade npm dependency, I'll accept it (that's strange dependabot did not proposed it already ^)
- Then Mega-Linter will automatically detect that there is a new markdown-table-formatter version and use it in [insiders version](https://github.com/nvuillam/mega-linter/blob/master/CHANGELOG.md#insiders-master)
- **insiders version** will become V4 version when I'll create a new Mega-Linter release :)

**Comment by tpansino** [comment]
@nvuillam FYI - I did read your `CONTRIBUTING.md` guidelines. The `npm run lint:fix` made several changes in unrelated files, but I didn't want to clutter this PR, let me know if you'd prefer otherwise. Also, I could not get the tests to run, got an error about the semicolon after `"use strict";` in the underlying VSCode extension package :man_shrugging: 

Also, are you aware the VSCode package has a CLI of its own? If yes, I'm curious what the original reason was for creating this wrapper?

**Comment by nvuillam** [comment]
Here is the story for the wrapper :) https://github.com/darkriszty/MarkdownTablePrettify-VSCodeExt/issues/49 (tldr: the proposed CLI does not accept files, its maintainer advised me to create this repo ^^)

**Comment by nvuillam** [comment]
@tpansino New version of markdown-table-formatter is now available in **insiders** version , you can check if it works like you need :)

I will be released in main version **V4** probably in a few days :)

**Comment by tpansino** [comment]
@nvuillam ✅ It works great! Thank you for the quick turn-around!

**Comment by nvuillam** [comment]
You're welcome :)
